# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!

target 'iosApp' do
  # Pods for iosApp
  pod 'composeApp', :path => '../composeApp'
  pod "onnxruntime-objc", "~> 1.18.0"
end
