# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'iosApp' do
  # use_frameworks! :linkage => :static

  # Pods for iosApp
  pod 'composeApp', :path => '../composeApp'
end
