name: Build IPA

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout my repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'

      - name: Setup Cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          podfile-path: iosApp/Podfile.lock

      - name: Pod Install
        run: |
          cd iosApp
          pod install
          
      - name: Archive
        run: |
          cd iosApp
          xcodebuild \
          -workspace iosApp.xcworkspace \
          -scheme iosApp \
          -archivePath build/iosApp.xcarchive \
          -sdk iphoneos \
          -configuration Release \
          -destination generic/platform=iOS \
          clean archive

      - name: Export unsigned IPA
        run: |
          cd iosApp/build/iosApp.xcarchive/Products/Applications
          mkdir Payload
          mv mahjongutils.app Payload
          zip -qq -r -9 iosApp-unsigned.ipa Payload
          mv iosApp-unsigned.ipa ../../..

      - name: Upload the Build Artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: distribution
          path: iosApp/build/*.ipa

      - name: Upload Release Assets
        if: ${{ github.event_name == 'release' }}
        uses: AButler/upload-release-assets@v3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          files: iosApp/build/*.ipa
